### ISSUE TITLE
Allow inclusion of libraries as relative paths

### ISSUE THREAD

**Issue by jonaskrask** [jonaskrask/vdm-vscode#108]
Related to #74.

It would be nice if the libraries were included as relative paths, such that you can export/share projects without having to change the settings file.

**Comment by jonaskrask** [comment]
@FrederikPM could this be something for you?

**Comment by FrederikPM** [comment]
What should the paths be relative to? Should we make it so that we have a "userLibs" folder next to the "libs" folder and then let the user add/remove libraries from the "userLibs" folder instead of simply include paths to library jars as it is now.

**Comment by nickbattle** [comment]
The only sensible choice is relative to the project, surely? Then we can "lift" a project and drop it elsewhere.

**Comment by FrederikPM** [comment]
Yes this works. However, due to the nature of VSCode settings, I think we and the user need to be clear on the different levels of settings, i.e. user, workspace and folder. We would expect the user to place the relative path at the folder level, however do we then merge library paths from the folder level with the workspace and user levels or de we expect the user to manage libraries only at the folder level? and if we choose to merge, then in the case of multiple identical jar names which level takes precedence?

**Comment by nickbattle** [comment]
To me, relative paths in user or workspace settings make less sense because it's not obvious what they are relative to. Folder settings are obviously relative to the folder.  If we merge and there are duplicates, shouldn't we just warn them somehow and then (I would say) folder > workspace > user.

I don't imagine people will use dozens of libraries, and we want to encourage them to use just the libraries that they need for each project (otherwise models will always take a long time to type check etc). So I think folder based library inclusion isn't that useful(?).

**Comment by FrederikPM** [comment]
I have implemented a solution where we merge libraries from the different setting levels. It took some time as there were a number of edge cases and "gotchas" with extracting the state of settings at the different levels. However, it seems that there is no way to specifically get the user level setting. It is only possible to get either the workspace level setting if that is defined or otherwise the user level setting.
So this could potentially confuse some users if they are using both levels.
There should be a VSIX with the latest action for the branch [fpm/108](https://github.com/jonaskrask/vdm-vscode/actions/runs/1916898730) if you want to try it out.
