### ISSUE TITLE
Types can be accessed without importing

### ISSUE THREAD

**Issue by paulch42** [jonaskrask/vdm-vscode#14]
When a type from another module is referenced in a module it must be imported. This constraint is checked for value, function and operation definitions. However, when a type from another module is referenced in a type definition with its fully qualified name, e.g. `MyModule'MyType`, then the import constraint is not checked.

A side effect of this is that F12 over `MyModule'MyType` does not go to the definition of `MyType` in module `MyModule` unless it is imported.

**Comment by nickbattle** [comment]
Interesting case, thanks!  I'll have a look, but I can guess what's going on. The type checker is trying to understand as much as possible about all of the types in the spec, and does not constrain itself by imports/exports while doing this. It sounds like it then does not check the import status of each type, though I can't see why that should confuse F12.

I'll take a look... :-)

**Comment by nickbattle** [comment]
So I've looked more closely at this, and it is as I suspected: the initial type resolution for modules disregards the imported scope, and the type is not checked again afterwards. I remember doing this (back in 2007 or so!) because I could not solve a host of other problems to do with multi-module type resolution. But making the obvious change now, to type-resolve each module using the module's import scope, seems to work correctly. It certainly raises an error for non-imported types, and all of the tests that I have also seem happy. F12 works correctly once the type is imported, as you say.

I want to test this more thoroughly before releasing it though. I will separately send you and Leo a jar to see whether this causes problems with any of your specs - between the pair of you, I think we cover the most complex multi-module models.

**Comment by nickbattle** [comment]
As discussed by email, there was a good reason for the multi-module type resolution phase, and replacing that as above does cause problems in more complex specifications. The fix is to leave type resolution as it stands, but to explicitly check during the type checking phase that referenced types are imported correctly. The change is currently in the development branch and seems to be working, but I'd like to get feedback from Leo before committing.

**Comment by nickbattle** [comment]
OK, Leo is happy with this too now, though he had many more occurrences of the wrong behaviour. I've pushed the changes into the master branches ready for release in 1.0.5.
