### ISSUE TITLE
Fix listing of functions and operations that are static.

### ISSUE THREAD

**Issue by FrederikPM** [jonaskrask/vdm-vscode#148]
Functions and operations that are static are listed under "Statics" at a VDM++ breakpoint as well as values but these probably shouldn't be there.

**Comment by nickbattle** [comment]
This should be fixed in the latest push. Can you give it a try?

**Comment by FrederikPM** [comment]
I'm not sure how to test this. But if you have already fixed and tested the issue we can just close it :)

**Comment by nickbattle** [comment]
I tried it with the example that I first noticed it with - which is fixed, but repeating that test doesn't add much. You just need a VDM++ spec, which has some static instance variables and/or value constants. Then run to a breakpoint in an operation, so that these statics should be in scope. You'll see a section in the "Variables" view titled "Statics". That used to include the static data and list the operations/functions in the class. Now it should just list the data.

**Comment by FrederikPM** [comment]
I have tested with the PacemakerSeqPP example by debugging the World operation in World. It does not show a 'Statics' section for the static instance variables, these are shown under 'World`self' in the 'Arguments' section. Is this as expected or have I misunderstood something?

**Comment by nickbattle** [comment]
Hmmm. OK, let me have a look.

**Comment by nickbattle** [comment]
Ah yes, sorry, you have to be in a "static" context - so typically having invoked a public static operation. It's OK, I've given it a quick test on the spec below. You see the "Statics" section doesn't have op/fns...

![image](https://user-images.githubusercontent.com/1751423/166677578-d6374e6e-ba65-4cf2-9dd1-b31c2ae98f5a.png)
