### ISSUE TITLE
Connect ECONNREFUSED error on launch

### ISSUE THREAD

**Issue by nickbattle** [jonaskrask/vdm-vscode#38]
You sometimes see an error dialog "connect ECONNREFUSED 127.0.0.1" pop up when you attempt to launch an execution. This is connected to bug #23 - it is because you have not opened any VDM source files in the project for which the launch applies. Opening a file starts the LSP/DAP server which (subsequently) responds to the launch request.

The fix for #23 will hopefully automatically start the server when a launch is made.

You sometimes also see a launch pause, without this giving error, but still fail to execute anything. This is the same problem, but you only seem to get the error dialog if you have started server for a *different* project folder within the same workspace.

**Comment by jonaskrask** [comment]
Note to self:
I see an error like: "connect EADDRNOTAVAIL 127.0.0.1", think this is the same. This happens because the extension registers a Debug Adapter Descriptor Factory for "vdm" type debug configurations when a VDM file is opened. When a debug session is (attempted) launched for another workspace the factory is not able to find the client and will try to connect to "undefined".
For the moment changed to a slightly improved message and force VSCode to open a file from the workspace folder to launch the client, then the user will be able to retry and succeed in the launch. **This should be improved** so that the extension starts the client for the workspace folder and retries the Debug launch, however, atm. I can't find a way to reliably know if the client is ready....
