### ISSUE TITLE
Improve Debug launch configuration options

### ISSUE THREAD

**Issue by jonaskrask** [jonaskrask/vdm-vscode#54]
A basic debug launch configuration interface was created in #36, but there is still several settings from the overture interface that are not available

**Comment by TomMontout** [comment]
Currently added java code generation options. Will start working on the launch configuration now

**Comment by nickbattle** [comment]
Note that issue #22 adds a new "remoteControl" field to launch configurations. These are mutually exclusive with the "command" field (ie. you can have one or the other, but not both).

**Comment by jonaskrask** [comment]
It should be easy enough to add some safety mechanism that checks if both are present in the run configuration file, maybe I can instruct Tom how to do so.

**Comment by jonaskrask** [comment]
Update: check between "remoteControl" and "command" implemented

**Comment by jonaskrask** [comment]
Status on features that are missing:

![image](https://user-images.githubusercontent.com/17763798/153592634-ac0271ad-7f34-4c4d-90c9-5514548bbdfb.png)
![image](https://user-images.githubusercontent.com/17763798/153592698-569cae1b-fecb-477c-829b-b8f1f9fbe406.png)

Don't know if all of these should and can be included. But we should probably make a list of the ones we want to include.

**Comment by FrederikPM** [comment]
@nickbattle do you have an overview of which of these additional debug options should be included?

**Comment by nickbattle** [comment]
Hmm... well, these options are a selection of those available in VDMJ's properties file. We already have a way to set "raw" properties via JVM arguments, but that is fairly crude. It would perhaps be nicer to create a UI for all(?) VDMJ properties. You can see the complete list (which isn't quite the same as Overture) in vdmj/src/test/resources/vdmj.properties. The values in this file are the defaults (that you get if you don't set the property).

There are a couple we have to omit, like vdmj.parser.tabstop, which has to be set to 1 for the LSP location process to work. But most of them are potentially user configurable.

**Comment by FrederikPM** [comment]
Would we still use JVM arguments to set these values or should we do something like generating a properties file from which VDMJ can load the values?

**Comment by nickbattle** [comment]
If these are changes that can be set per-launch, rather than per-project, it makes sense to add them to the launch JSON message (perhaps in a sub-object). If we rely on passing JVM arguments, these are settings that apply to the whole project for all launches - such a thing may be useful, and that would warrant a "vdmj.properties" file, probably in the .vscode folder.

So we need to divide VDMJ properties into those that are for a launch and those that are for the whole project. Remember, in command-line VDMJ those are the same thing(!), but for VSCode we have multiple launches even though the Server is only started once.

Can you have a stab at dividing the properties into those two groups?

**Comment by nickbattle** [comment]
Thinking about it... perhaps the easiest thing would be to use a UI to create a .vscode/vdmj.properties file for every property, which the Server reads at startup, but then we also allow per-execution overrides via the launch configuration?

That way, you could choose whether to make settings for the whole project or per-launch.

I would probably have to re-read the properties for each new launch, so that there aren't "hangovers" from the last run still in the active property settings. But this approach does seem to cover all bases?

**Comment by FrederikPM** [comment]
Yes, that sounds like a better idea. I'll have a go at it on the client side :)

**Comment by nickbattle** [comment]
While we're changing the launch JSON, perhaps we could make the settings like "measureChecks" and "preConditionChecks" also sit in a sub-object? It's a bit strange to have everything at the top level.

I'll push a tweak to VDMJ to allow it to use a named properties file. But I'll have to make more changes to reset to the defaults after a launch (same for the Settings above actually - currently, if you set one, it stays set for subsequent launches!)

**Comment by FrederikPM** [comment]
Yes I'll implement that

**Comment by nickbattle** [comment]
I've just pushed some VDMJ and LSP changes to pick these up. So it will look for a file called `.vscode/vdmj.properties` and load that at startup (so property changes require a "restart"). Then it will override these and any "Settings" via the launch JSON. At the end of the launch session, it will restore the properties from the file and Settings to their defaults. There are Diags to tell you what's going on.

Obviously you can't change Settings.dialect. I see there is a "strict" VSC setting, but I can't see what that does? They cannot change usingCmdLine.

There are a few properties that we shouldn't allow them to change: vdmj.parser.tabstop, vdmj.cmd.plugin_packages, vdmj.debug.link_class. Either because they would break the system or are irrelevant to VSC.

**Comment by nickbattle** [comment]
PS. I just changed the new property name to `vdmj.parser.external_readers`, with an underscore, which is the convention for multi-worded values :)  Sorry for the nuisance.

**Comment by FrederikPM** [comment]
I have pushed an implementation to [fpm/54](https://github.com/jonaskrask/vdm-vscode/actions/runs/2063549955). Can you try it out when you have the time? :)
Changing the VDMJ properties  for a given folder is done via the command palette with the command `Change project wide VDMJ properties`. If no vdmj.properties file is present for the project in `.vscode` it loads the file from the extensions resources folder. Any changes will be saved locally in a vdmj.properties file in `.vscode`.

For the launch configuration it should now support "settings" and "properties" as described above. As default the "settings" object is always auto filled with every property set to true. The "properties" object are always added but with no properties.

**Comment by nickbattle** [comment]
OK, I'll take a look, hopefully later today. The .vscode properties can just contain the changed values, if that helps. It isn't harmful to have every entry, but if people want to manage the file by hand, it might be nicer to just have the changes?

The default settings as true would be OK, and (override) properties as empty makes sense.

It looks like "strict" and "verbose" turn on `-Dvdmj.strict=true -Dvdmj.verbose=true`, though I don't think I'm currently dealing with those in the Server... will fix :-)

**Comment by nickbattle** [comment]
> though I don't think I'm currently dealing with those in the Server... will fix :-)

LOL, it is in there, but I'd completely forgotten about it! Sorry for the confusion.

**Comment by FrederikPM** [comment]
No problem :)
I'll make it so that the file in .vscode only contains the changes.

**Comment by nickbattle** [comment]
So this does work, but the way we input values in these VSCode dialogs is very confusing - you have to select what you want, then update the value(s), which I find very unintuitive. It would almost be better to just populate/open the vdmj.properties file in an editor. At least then we could include the explanatory text for each one too?

The launch configuration looks fine except that the `"vdmj.mapping.search_path": null` entry complains that it should be a string? (null is fine as a default value here though), and `"vdmj.parser.external_readers": []` is an array (I agree an array makes sense, but the property handling is a CSV string and I'd rather not have two syntaxes! So this should also be a string or null).

If you populate the defaults when they create "properties", wouldn't it be consistent to do the same for "settings" and have neither unless they're created by the user?

**Comment by nickbattle** [comment]
Also noticed that the "hover" help text for the `<.suffix>=<class>` in external_readers is broken and has a typo anyway - I guess you have to quote the angle brackets or equals sign somehow?

If we wanted to be really smart, we could omit the `vdmj.rt.*` options unless the project is VDM-RT? The other options apply to all dialects, but the "rt" ones are special.

**Comment by FrederikPM** [comment]
Would empty string be an okay default for `vdmj.mapping.search_path` and `vdmj.parser.external_readers`?

**Comment by nickbattle** [comment]
Yeah, let's try it with a command that just populates/opens the raw properties file. I know the built-in VSCode dialogs are very limited, which is very strange (we had a similar problem with the Launch/Debug lens commands).

If I create a new launch, I get the following:
```
		{
			"name": "Debug Console",
			"type": "vdm",
			"request": "launch",
			"noDebug": false,
			"settings": {
				"dynamicTypeChecks": true,
				"invariantsChecks": true,
				"preConditionChecks": true,
				"postConditionChecks": true,
				"measureChecks": true
			},
			"defaultName": null
		},
```
If I then add a "properties" section, it populates all the defaults for that. All I'm saying is that if it's not adding properties for me, it probably shouldn't add settings either. It's fine that it populates them with defaults though.

I think you'll get away with a blank string, but it's not ideal. Really we need to find a way to declare a field as a nullable string. There must be a way, surely??

**Comment by nickbattle** [comment]
Ugh... just realised there was a bug in the way it was parsing -strict and -verbose options. No wonder I couldn't seem to get them to work!  Anyway, pushed a fix now.

@leouk I know you find this useful, so now if you set those options in your folder settings, the LSP Server will start dumping on you :-)

**Comment by FrederikPM** [comment]
I have implemented the changes that we discussed which are available on [fpm/54](https://github.com/jonaskrask/vdm-vscode/actions/runs/2070099304) so you can give it a go :)
For the broken tooltip it seems like VSCode treats any sequence of characters encased in `<>` as some special case that gets stripped from the text somewhere in the process of piping the description text from the package.json file to the tooltip text shown in the configuration. I cannot figure out how to escape the symbols other than adding any symbol or a white space before the first character, e.g. `< class>`. Alternatively we could also use some other symbols than the `<>` combo.

**Comment by nickbattle** [comment]
LOL, well angle brackets are just a convention. How about using square brackets, like `[.suffux]=[class]`?

I'll give that build a try later, thanks.

**Comment by nickbattle** [comment]
Yes, editing that properties file seem much better to me - especially since the defaults are populated, together with their explanations inline. By the way, that file is "officially" at src/test/resources in VDMJ. It may change from time to time, so perhaps you can check for that in the build of the extension somehow?

The launch JSON looks good too. It seems you fixed the null string problem? It now has nulls without warnings, which I think is right.

Looks good!

**Comment by nickbattle** [comment]
PS.  The "RT" properties are still being included for non-RT launches. Can we suppress that easily?

**Comment by FrederikPM** [comment]
Some script that copies the newest jar versions together with the newest version of the vdmj.properties file would be nice to have when building/releasing the extension.

Yes, allowing a null string turned out to simply be allowing multiple types, i.e. string and null.

I'm looking into if it is possible to omit the RT properties for non-RT launches. However, the immediate conclusion is that it cannot be done easily or rather it would require a lot of identical schema lines in the package.json file.

**Comment by nickbattle** [comment]
RT option filtering isn't super critical if it's not that simple. So is this issue done now?

**Comment by FrederikPM** [comment]
Yes. I'll merge it into development
