### ISSUE TITLE
Add example project, copy permission denied

### ISSUE THREAD

**Issue by jonaskrask** [jonaskrask/vdm-vscode#59]
It seems the copy operation we use for "import example project" is not allowed to copy subfolders. I get the following errors when importing:
**AutomatedStockBrokerPP**
Copy example files failed with error: Error: EPERM: operation not permitted, copyfile 'c:\Users\au543131\Documents\Github\vdm-vscode\resources\examples\VDM++\AutomatedStockBrokerPP\lib' -> 'c:\Users\au543131\Downloads\AutomatedStockBrokerPP\lib'

**BuslinesWithDBPP**
Copy example files failed with error: Error: EPERM: operation not permitted, copyfile 'c:\Users\au543131\Documents\Github\vdm-vscode\resources\examples\VDM++\BuslinesWithDBPP\lib' -> 'c:\Users\au543131\Downloads\BuslinesWithDBPP\lib'
c:\Program Files\Microsoft VS Code\resources\app\out\bootstrap-fork.js:5
Copy example files failed with error: Error: EPERM: operation not permitted, copyfile 'c:\Users\au543131\Documents\Github\vdm-vscode\resources\examples\VDM++\BuslinesWithDBPP\src' -> 'c:\Users\au543131\Downloads\BuslinesWithDBPP\src'

**Comment by nickbattle** [comment]
I also noticed that, if you're working in a workspace, the import can be very confusing because it seems to open a "child" window with the imported project, but not import it into the workspace that you have open in the "main" window. I can imagine why, but intuitively, you want to "Add Folder to Workspace" as well as importing it somewhere?
