### ISSUE TITLE
Incorrect "Debug session already running"

### ISSUE THREAD

**Issue by jonaskrask** [jonaskrask/vdm-vscode#60]
From correspondence with Leo:

> Here is what I see on the reload scenario I was asking about. 
> 
> The debugger was running. 
> I changed the spec. 
> I clicked the reload button. 
> It failed with the spec errors. 
> I fixed the spec, no errors.
> I start debug again (via menu).
> Got the warning there is already one in place. 
> But then nothing got “reloaded”. 
> Had to restart VSCode for it to “go”.
> 
> There was no way to restart/stop the debugger or reload the spec. 

This is probably due to incorrect tracking of whether the debug session is running or not, we have to find a better way to track this..

**Comment by nickbattle** [comment]
I've tweaked the restart handling so that, if the specification has errors, it returns the same terminate/exit messages that it would for a "stop", rather than an OK response. That may help us to distinguish the cases, since the client can't really know whether the spec has errors (the presence of "problems" may not be errors as such?)

**Comment by jonaskrask** [comment]
I have made some changes to how we track running sessions, and added a small sanity check
