### ISSUE TITLE
Type checking errors and warnings are lost

### ISSUE THREAD

**Issue by paulch42** [jonaskrask/vdm-vscode#7]
Type checking is invoked when a file is saved, and any errors and warnings are highlighted in the editor window and listed in the problems pane. When I start typing to address the first of these all the errors and warning disappear making it difficult to address all issues without saving multiple times to re-invoke the type checker.

A nice feature of Overture is that it retains the error annotations till the next save allowing you to easily identify and correct multiple errors without saving.

**Comment by nickbattle** [comment]
Good point. This is because the LSP protocol requires us to send back all errors (I think). When you start typing, it is doing a lightweight syntax check of just that one file. So it only sends local syntax errors as soon as you type.

I think we need to maintain some sort of "persistent errors" that are always sent (until a save), and combine that with "transient errors" that are raised as you type. It may be that the two clash, though you can see something similar with the Eclipse Java editor, where "tc" errors get slightly confused as you type and then magically clean themselves up when you save.

**Comment by nickbattle** [comment]
This is now fixed. It works more or less as you would expect, that is, the error markers for TC errors remain in the text and get a little confused as you correct them in the editor, but then when you save everything is cleaned up. The TC error messages remain in the problem window as required, and syntax errors come and go as you type.

**Comment by nickbattle** [comment]
Fix is in LSP 4.4.2-SNAPSHOT for now.

**Comment by jonaskrask** [comment]
available in release 1.0.3
