### ISSUE TITLE
Change "Add VDM Library" to discover libraries based on classpath

### ISSUE THREAD

**Issue by jonaskrask** [jonaskrask/vdm-vscode#74]
Based on issue #73.

Going forward, we need a way to discover the (arbitrary) libraries on the classpath and allow the user to select from all of them when they go to the "Add VDM Library" dialog. For example, we can include a MANIFEST entry in library jars that describes them, so that they can be discovered on the fly.

**Comment by nickbattle** [comment]
Presumably VSCode uses a JSON object to represent the data to display in the menu that is offered to select a library to add. So perhaps a simple way to move this forward would be to add a similar JSON structure to each library jar's META-INF folder. The client would still need to collect several such structures together and convert them, but it would presumably make the job easier?

Also, note that some libraries may require more than one VDM source to be added to a project.

So something like:
```
{
    "name" : "Bullet",
    "description" : "The Bullet physics library",
    "dialect" : "VDM-SL",
    "files" : [ "Bullet.vdmsl", "Collision.vdmsl", "Dynamics.vdmsl", "Linear.vdmsl" ] 
}
```

**Comment by FrederikPM** [comment]
Hi @nickbattle. I'm currently working on this issue.
I think that a JSON structure like the one you have outlined would be ideal. As far as I can tell it carries all the information needed to be displayed to the user and for us to extract and copy the files.

**Comment by FrederikPM** [comment]
Ah okay. I see.
Then I think that we should move forward with the structure that you have suggested :)

**Comment by nickbattle** [comment]
Well, it's still fluid. The JSON will just be created manually, so we can make it as convenient as you want. Would it help to have a top level division by dialect - I'm thinking of how the UI would work? You know the dialect of the project, so you could then immediately narrow down what was available from each jar?

So...
```
{
    "VDMSL" :
    {
      {
          "name" : "IO",
          "description" : "The IO library",
          "files" : [ "IO.vdmsl" ],
          "depends": null
      }
      etc...
    },
    "VDMPP",
    {
    },
    "VDMRT",
    {
    }
}
```
We should probably keep the "depends" namespace flat for now. So a dependency for "XYZ" means that there needs to be another section or another library with "name":"XYZ" for the same dialect.

**Comment by FrederikPM** [comment]
Yes a top level division by dialect would be ideal. That would indeed make it easier to narrow down what's available from the jar.
So the depends part can point to both another library defined in the top level dialect section or independent files like 'x.<dialect>'?

**Comment by nickbattle** [comment]
Well, a dependency is just on a "name" as I see it. So that name would then have to be located, either in the same JSON "file" or within the JSON file of another library jar.

As I imagine it, there would be something like a "resources/libraries" in the extension folder, where (somehow?) people can add several libraries (stdlib would come for free). Each jar has a MANIFEST entry with a JSON file that describes its own sources and dependencies. The UI has to offer all of the "name/descriptions" that are available, let the user select the one(s) they want, and then add the corresponding files to the project. I suppose the files could be in subfolders, both in the jars and in the project (within "lib").

The dependency resolution then has to scan over all of the JSON files, starting with the user's selected names and adding any dependencies recursively. If there's a missing dependency, we let them know.

Finally, a list of library jar names is collected so that these can be added to the Java classpath of the server. That's maybe something to discuss with @jonaskrask :-)

**Comment by FrederikPM** [comment]
@nickbattle I have made it so that the logic now looks for a json file with a given name in the META-INF. The logic expects the json format to be like you described above. It can then present the user with the libraries (and their descriptions) to choose from. When the user has chosen any number of libraries, the logic extracts the needed files together with any dependecies from the jars and copies the resulting files to a lib folder in the project.
Should the logic look for dependencies across jars or expect each library to be self contained within its jar?
I talked with @jonaskrask and we have made so that the user can add library jars using the "Class Path Additions" setting for the extension. This setting will then as default include the stdlib jar.

**Comment by nickbattle** [comment]
@FrederikPM This sounds great! If you tell me the name you expect for the JSON file, I can add it to the stdlib build - perhaps easiest if you send/attach a file with the name and format you expect?

I don't see why we should limit dependencies to be within a jar, though I agree the stdlib dependencies are in one jar (of course). But in general, a 3rd party user lib may depend on something from stdlib or another jar.

Are you saying that the user has to manually edit the classpathAdditions? Can we not automagically add the ones that we select from the library dialogue? (Though of course it's fine to do that as a stopgap).

**Comment by FrederikPM** [comment]
[Here is the file that I have used for testing](https://github.com/jonaskrask/vdm-vscode/files/7899555/library_defintions.txt)
The name can of course be changed if you have a good idea for a better name :)

Okay. Then I will scan across all the jars for dependencies.

Yes the user has to add, through the classpathAdditions setting, library jars manually and then the user can select any libraries from the jars that should be included in a given project. All library jars, also those from which the user haven't selected any libraries, will of course then be on the class path.
Would you prefer if the class path only includes the library jars containing the libraries that the user has selected?

**Comment by nickbattle** [comment]
OK, thanks. I'll try to think of a good name :^)

Ah I see: the classpathAdditions is the "base" that the libraries are chosen from (plus stdlib implicitly, I hope)? I imagined you having to put them in a standard folder somewhere, but perhaps the classpathAdditions is reasonable. It might cause a problem if (say) you had several versions of the same library (ie. the same Java class names) that you wanted to switch between. If they were all on the classpath, you'd always get the "first"; if they were selected from a standard folder, the classpath could then have just the libraries that you needed. But then I guess you could edit the classpathAdditions too, so it's not impossible.

Hmmm... not sure. @jonaskrask, what do you think?

**Comment by FrederikPM** [comment]
Great! The new `stdlib.jar` works without issues :)

For now I have added two new configuration settings for the extension. One called "VdmLibraries" that is an editable list of paths like the "classpathAdditions" setting but instead intended for library jars. The other called "includeDefaultLibraries" which allows the user to disable (it is enabled by default) the inclusion of the "default library jars" that ships with the extension located in 'resources/jars/libs' so that the user can provide their own versions of the default libraries if they wish. For now that folder location only contains the `stdlib.jar`.
Any library jars found in "VdmLibraries" and the default library paths (if enabled) will be added to the classpath that is passed to the process that spawns the language server. So the language server will have access to the jars independently from whether the user choses to add any of the libraries or not.

The user would still have to edit these paths as needed to circumvent the issue that you described above. 
The "add libraries" dialog logic needs to be changed a bit if we want to be able to present the user with the same library but in different versions. As it is now the dialog logic just uses the first library that it encounters with a given name and then informs if it finds libraries with identical names (across all library jar files). 
If we start to consider different versions of libraries then would we not also have to consider matching with correct versions of implicit dependencies and implicit transcending(is this the word?) dependencies or am I over complicating it? :)

**Comment by nickbattle** [comment]
This sounds like a really significant enhancement, great work!

Let's not overcomplicate things for now. I'm sure that multiple library versions isn't something that most people will need (and they can achieve the effect anyway, albeit by having to fiddle their settings). I wouldn't want to delay bringing this to users, just because it can't support multi-versioning.

We'll need a document at some stage, or a section in an existing Guide, that explains how to create your own libraries. But that can be a separate issue.

Can I try this with a VSIX anywhere?

**Comment by FrederikPM** [comment]
Okay. I also think that a separate issue for the some sort of documentation of how to create your own libraries would be a good idea.
Yes it would be great if you could try it out as there could be something that I have overlooked/missed in the implementation.
I have created a workflow file so that we from now on can have Github actions create a VSIX file whenever a push to a branch is made. So you should be able to download the VSIX [by clicking on the latest action for the fpm/74 branch](https://github.com/jonaskrask/vdm-vscode/actions/runs/1739107413).

**Comment by nickbattle** [comment]
There is an FMI "Plugfest" coming up tomorrow and Wednesday, and I'm using one of my VDM models to demonstrate the work that we've been doing. So I don't want to try anything new for a couple of days(!!). But I'll get back to this later in the week. Having a VSIX built automatically will help a lot, though we need to know which branch to look at too :-)

**Comment by nickbattle** [comment]
Sorry for the delay. I just had a quick look at this (the fm74 VSIX) and it looks nice! A few thoughts:

- I need to put better descriptions in the stdlib JSON file :-)

- If you disable the "include stdlib" option, but don't have any other lib paths in settings, the Add Library dialogue isn't very helpful (it's blank). Could we tweak it that so that (say) there is a link to add the setting(s)? Or perhaps add a comment that tells them what to do to get a list of libs to choose from?

- User lib jars/folders get added to the classpath, even if they don't select libraries? That may be fine. I was wondering how you would know to edit the classpath if they added a lib and then manually deleted the lib/XXX.vdmsl file. But if they're always included, that's not a problem.

- If I add a folder, does that mean "all the jars in here" or is the folder link an unzipped jar format?

- I haven't checked inter-jar dependencies, but intra-jar deps certainly work (though dependencies are added silently)

**Comment by nickbattle** [comment]
Could we change the option to "vdm-vscode.server.libraries.VDMLibraries"? It looks strange to have mixed case "Vdm" :-)

**Comment by FrederikPM** [comment]
No problem and thanks for trying out the VSIX.

1. Hehe. Yes that would be good :)
2. I'll look into tweaking the dialog whenever "include stdlib" is disabled and the user haven't added any libs.
3. Yes. Whatever jars (from paths pointing directly to jars and from paths pointing to folders containing jars) are in the editable list of the setting "VdmLibraries" (and also our stdlib if the setting is enabled) gets included in the classpath that is used to spawn the server process . If any changes are made to the library settings the extension is reloaded effectively respawning the server with a classpath that reflects the changes. So it should not be a problem if the user manually removes a library file from a project.
4. Adding a folder means all jars in the folder. Should this be clarified or changed?
5. Would it be better to display a message when adding a dependency instead of adding it silently?
6. Yes you're right. I will change the naming of the option :)

**Comment by nickbattle** [comment]
With (4), it's difficult to find succinct wording that is unambiguous. Sometimes, you just have to add more words!
With (5), it might be nice to pop up a brief notification to say, "I also included xxx, which is required by yyy" or similar?

**Comment by FrederikPM** [comment]
I have pushed the changes to fpm/74 if you want to try out the VSIX and see if the changes are intuitive.
The naming of the option "...libraries.VdmLibraries" has been changed to "...libraries.VDM-Libraries" which displays as: "Libraries: VDM-Libraries" in the settings tab. "...libraries.VDMLibraries" unfortunately displays as "Libraries: VDMLibraries" due to how VSCode transforms the setting id to a setting title.

**Comment by nickbattle** [comment]
We're away for a couple of days at the moment, but I'll definitely have a look at this later in the week :-)

**Comment by nickbattle** [comment]
I just realised: we might have a problem with "high precision" and libraries? In general, the Java parts of a library might be built for high or standard precision (not both), so the standard `resources/libs` copy of stdlib needs to be either the hp one or the standard one (remember the jar used to be under both jars/vdmj_hp and jars/vdmj).

It's OK for user-given classpaths (they just have to make that consistent with their high precision setting). But for the stdlib, I think we probably need vdmj/hp subfolders in libs? Or put libs under vdmj/vdmj_hp?

**Comment by FrederikPM** [comment]
Good catch. I haven't tought about that.
I'll make a 'libs' subfolder in vdmj and vdmj_hp and then fetch the correct version of the library depending on the state of the 'highPrecision' setting.

**Comment by FrederikPM** [comment]
The latest action for fpm/74 contains a VSIX for you to try out with the changes.

**Comment by nickbattle** [comment]
OK, that seems to work great! Thanks for the rapid fix :)

**Comment by FrederikPM** [comment]
Great. Then I'll merge into development and close this issue :)

**Comment by nickbattle** [comment]
Oh! One last thought, sorry... but I notice the classpaths have an explicit stdlib jar, but a "vdmj/*" pattern for the others. Shouldn't it have "vdmj/libs/*" so that we can pick up more built-in libs in future? (Agreed, it will work fine while we have just one).

**Comment by FrederikPM** [comment]
No problem :)
I'm not sure I follow. The classpath that gets constructed and used to start the server will be recreated if the user changes any of the library settings. It should include any jars that we ship with the extension within the <vdmj/vdmj_hp>/libs folders explicitly.

**Comment by nickbattle** [comment]
OK, as long as they all get added explicitly that's fine. But wouldn't it be easier to always include `vdmj/libs/*` ?
