### ISSUE TITLE
Response message without id

### ISSUE THREAD

**Issue by jonaskrask** [jonaskrask/vdm-vscode#81]
After completing a "translate" request the server responds to the "workspace/didChangeWatchedFiles" request with a message without an id.

Log snippet attached.
[null id log.txt](https://github.com/jonaskrask/vdm-vscode/files/7761501/null.id.log.txt)

**Comment by nickbattle** [comment]
It's because the didChangeWatchedFiles message is a notification, and I'm treating it like a request. So the notification has no "id" field, but the response expects one. The fix is not to send a reply at all, unless the changed file produces errors/warnings, which themselves are notifications (exception Server to Client).

I'll see whether this works.

**Comment by nickbattle** [comment]
That seems fine now. The change file notification comes in and is handled, but no response is sent because the generated file is ignored and the spec has no (new) errors to report:
```
12:04:33.792: >>> LSP {"jsonrpc":"2.0","method":"workspace/didChangeWatchedFiles","params":{"changes":[{"uri":"file:///home/nick/vscode.tests/TestSL/.generated","type":1},{"uri":"file:///home/nick/vscode.tests/TestSL/.generated/latex%2022-12-2021%2C%2012.04.33","type":1},{"uri":"file:///home/nick/vscode.tests/TestSL/.generated/latex%2022-12-2021%2C%2012.04.33/modules.tex","type":1}]}}
12:04:33.794: New directory created: /home/nick/vscode.tests/TestSL/.generated
12:04:33.794: New directory created: /home/nick/vscode.tests/TestSL/.generated/latex 22-12-2021, 12.04.33
12:04:33.796: Ignoring file on dot path
```
If file changes cause a rebuild, you can get notification responses that contain no errors (ie. clearing any errors), but these are still notifications so I think it is as it should be.

**Comment by nickbattle** [comment]
Now available in "development".
