### ISSUE TITLE
Remove dependency on portfinder

### ISSUE THREAD

**Issue by jonaskrask** [jonaskrask/vdm-vscode#84]
Currently, we are using portfinder to find two available ports for each client/server. However, this library is not meant for production code. Furthermore, if two clients are started simultaneously a race condition is likely to occur, where the clients are attempting to connect to one or more of the same ports.

Considering if we should change the creation of the socket, such that the client launches it instead of the server...

**Comment by jonaskrask** [comment]
Likely the cause of #78

**Comment by nickbattle** [comment]
Unless I've misunderstood you, it's quite hard for the Client process to open a socket that a separate server process picks up?

I see what you mean about races though.

It probably doesn't help, but for neovim, we start the server process with a zero DAP port and then send back the port that was allocated by the server (in the init response experimental section). But you still have to allocate the LSP port.

Isn't a port-hunter just a matter of trying to bind to ports in a loop over a reasonable range? We could arrange for the server to produce a particular process exit code if it cannot bind the port, and retry, to defend against races?

**Comment by jonaskrask** [comment]
It should be pretty easy to create the socket and tell the server where to listen.
The difficult part is to look for a port and then let it go and have the server create a socket on that port. Because in the meantime there is a chance that someone else will grab the port. Also, there is the issue of knowing when the socket is open and ready.

Would it be an issue to add another launch point for lsp where you listen on the port instead of creating a socket?

That of course still leaves the DAP port where we as it is now probably need the server to own the socket... but that might be solved with the neovim approach?

**Comment by nickbattle** [comment]
We could try to do this, but I'm not sure that I can bind to an address if the same process has not accepted a connection. If you think this is possible, it should be easy to write two proof-of-concept classes in Java, one of which creates a socket and binds it to an address, and then spawns another process that waits for a connection on that address. Can you try that? (Because this is definitely not a standard pattern!)

If that works, then yes, we can use the neovim trick to pass back the DAP port.

**Comment by jonaskrask** [comment]
I might be saying it wrong.. but the idea is to have the client start the tcp/ipc server instead of the server doing that. This seems to be the way the guys at vscode imagined it should happen, see:
![image](https://user-images.githubusercontent.com/17763798/147238710-1b1d4eec-9fdf-4418-9a00-4803b347091f.png)

I have created an implementation of this on the "issue84" branch. If you set the experimental server setting true, it will select port 8000, if not it will grab a random port. I had it working with a "hacked" version of `LSPServerSocket.java` where `run()` is like this:
![image](https://user-images.githubusercontent.com/17763798/147238619-7933b108-1397-4158-98d7-fec0a4c44b45.png)

We can also make the experimental server setting connect as before if you would rather have that, but this will help with the testing :)

**Comment by nickbattle** [comment]
Hmm... OK, that's a surprise. I think you would have to have this as a "one-shot" connection, so without the while-loop since it is closed at the end. The DAP server has to be a while loop because its connection is closed and opened several times in a session as the user launches things. But as I mentioned, the DAP listener port is sent back with the LSP initialize response, so we could pass -dap as 0.

For experimental use, it would be much easier to have the server listen, otherwise the timing of setup between the debugged server and client would be awkward - basically the debugger has to be ready and listening first.

So how about I create a new LSPServerDebug that is as we currently have it, and I change LSPServerSocket to be similar to what you've done, but without the looping? You bind with 8000/8001 for the experimental one, and <random>/0 for the real one.

**Comment by jonaskrask** [comment]
Ah yes, didn't notice the while loop, was just focused on the socket.. Sounds good with your suggestion, perhaps keep LSPServerSocket as is, and make one called LSPClientSocket?

I will change the experimental use to the normal use.

What is the configuration called where I can pick up the DAP port?

**Comment by nickbattle** [comment]
Well, the convention is "LSPServer\<type\>" like LSPServerStdio, which is similar as a one-shot connection.

The initialize response `experimental` section has `"dapServer" : { "port" : 8001 }`

**Comment by jonaskrask** [comment]
Okay, let's do as you first suggested then.

**Comment by nickbattle** [comment]
I've just pushed something to development. It's hard for me to test(!) because the socket bind obviously fails unless someone else has set up the socket :-)
```
13:26:12.877: LSP VDM_SL Server listening on port 8000
13:26:12.894: DAP VDM_SL Server listening on port 8001
13:26:12.905: ERROR: LSP Server socket error: Connection refused (Connection refused)
```
(I'll change the LSP diag to say connecting to, rather than listening on)

**Comment by jonaskrask** [comment]
I have pushed the change to the `issue84` branch, however, I am still missing the change to the DAP handler

**Comment by jonaskrask** [comment]
Turned out to be a quick fix. Right now it is also set to use the '0' DAP Port in experimental use, is that okay?

**Comment by nickbattle** [comment]
Yes, that's fine for experimental too.

So if you push a VSIX, we can both switch over? It's just that this is a breaking change: we have to move together!

(I'll be away for a couple of hours)

**Comment by jonaskrask** [comment]
Great. I have merged it into the development branch with a new vsix

**Comment by nickbattle** [comment]
That seems to work perfectly, both with the internal server and an external experimental server :-)
